Przegląd danych

In [18]:
from pathlib import Path 
import pandas as pd
import numpy as np 

path = Path.cwd().parent/'data'/'raw'

df_2526 = pd.read_csv(path/'E0_2526.csv')

df_2526

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

In [19]:
df_2425 = pd.read_csv(path/'E0_2425.csv')
df_2425.head(10)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,16/08/2024,20:00,Man United,Fulham,1,0,H,0,0,...,1.86,2.07,1.83,2.11,1.88,2.11,1.82,2.05,1.90,2.08
1,E0,17/08/2024,12:30,Ipswich,Liverpool,0,2,A,0,0,...,2.05,1.88,2.04,1.90,2.20,2.00,1.99,1.88,2.04,1.93
2,E0,17/08/2024,15:00,Arsenal,Wolves,2,0,H,1,0,...,2.02,1.91,2.00,1.90,2.05,1.93,1.99,1.87,2.02,1.96
3,E0,17/08/2024,15:00,Everton,Brighton,0,3,A,0,1,...,1.87,2.06,1.86,2.07,1.92,2.10,1.83,2.04,1.88,2.11
4,E0,17/08/2024,15:00,Newcastle,Southampton,1,0,H,1,0,...,1.87,2.06,1.88,2.06,1.89,2.10,1.82,2.05,1.89,2.10
5,E0,17/08/2024,15:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.94,1.99,1.94,1.98,2.05,2.00,1.93,1.93,1.96,2.02
6,E0,17/08/2024,17:30,West Ham,Aston Villa,1,2,A,1,1,...,1.83,2.10,1.85,2.09,1.86,2.14,1.82,2.08,1.84,2.18
7,E0,18/08/2024,14:00,Brentford,Crystal Palace,2,1,H,1,0,...,2.07,1.86,2.06,1.88,2.11,1.88,2.05,1.85,2.07,1.92
8,E0,18/08/2024,16:30,Chelsea,Man City,0,2,A,0,1,...,1.94,1.99,1.96,1.97,1.96,2.00,1.90,1.96,1.93,2.07
9,E0,19/08/2024,20:00,Leicester,Tottenham,1,1,D,0,1,...,2.03,1.90,2.02,1.91,2.06,1.92,1.99,1.87,2.03,1.96

In [20]:
df_2324 = pd.read_csv(path/'E0_2324.csv')
df_2324.head(10)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,11/08/2023,20:00,Burnley,Man City,0,3,A,0,2,...,2.28,1.50,1.95,1.98,1.95,1.97,NaN,NaN,1.92,1.95
1,E0,12/08/2023,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,...,2.63,-2.00,1.95,1.98,1.93,1.97,2.01,2.09,1.95,1.92
2,E0,12/08/2023,15:00,Bournemouth,West Ham,1,1,D,0,0,...,2.12,0.00,2.02,1.91,2.01,1.92,2.06,1.96,1.96,1.91
3,E0,12/08/2023,15:00,Brighton,Luton,4,1,H,1,0,...,2.48,-1.75,2.01,1.92,2.00,1.91,2.14,1.93,2.00,1.86
4,E0,12/08/2023,15:00,Everton,Fulham,0,1,A,0,0,...,1.71,-0.25,2.06,1.87,2.04,1.88,2.08,1.99,1.98,1.88
5,E0,12/08/2023,15:00,Sheffield United,Crystal Palace,0,1,A,0,0,...,1.53,0.25,2.10,1.83,2.10,1.84,2.12,1.86,2.05,1.83
6,E0,12/08/2023,17:30,Newcastle,Aston Villa,5,1,H,2,1,...,2.22,-0.75,1.84,2.09,1.85,2.09,1.87,2.13,1.82,2.06
7,E0,13/08/2023,14:00,Brentford,Tottenham,2,2,D,2,2,...,2.15,0.00,1.88,2.02,1.89,2.03,1.95,2.05,1.89,1.98
8,E0,13/08/2023,16:30,Chelsea,Liverpool,1,1,D,1,1,...,2.52,0.25,1.98,1.92,2.00,1.93,2.03,2.08,1.91,1.96
9,E0,14/08/2023,20:00,Man United,Wolves,1,0,H,0,0,...,2.37,-1.50,1.80,2.00,1.82,2.08,1.88,2.14,1.82,2.05

Wybiore teraz kolumny które mi posłużą do analizy i wytrenowania modelu.

In [21]:
SELECTED_COLUMNS = [
    # Podstawowe informacje i wynik
    'Date', 'HomeTeam', 'AwayTeam', 
    'FTHG', 'FTAG', 'FTR', 
    'HTHG', 'HTAG', 'HTR',
    
    # Statystyki meczowe
    'HS', 'AS',     # Strzały
    'HST', 'AST',   # Strzały celne
    'HF', 'AF',     # Faule
    'HC', 'AC',     # Rzuty rożne
    'HY', 'AY',     # Żółte kartki
    'HR', 'AR',     # Czerwone kartki
    
    # Kursy bukmacherskie (rynek 1X2)
    'AvgH', 'AvgD', 'AvgA',    # Średnia rynkowa
    'B365H', 'B365D', 'B365A', # Bet365
    'PSH', 'PSD', 'PSA'        # Pinnacle
]

In [22]:
new_df_2526 = df_2526[SELECTED_COLUMNS]

new_df_2526.head(10)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,...,AR,AvgH,AvgD,AvgA,B365H,B365D,B365A,PSH,PSD,PSA
0,15/08/2025,Liverpool,Bournemouth,4,2,H,1,0,H,19,...,0,1.31,5.96,8.31,1.30,6.00,8.50,1.28,6.56,9.07
1,16/08/2025,Aston Villa,Newcastle,0,0,D,0,0,D,3,...,0,2.30,3.56,2.94,2.25,3.50,2.90,2.24,3.72,3.13
2,16/08/2025,Brighton,Fulham,1,1,D,0,0,D,10,...,0,1.92,3.62,3.91,1.91,3.60,4.00,1.94,3.73,3.98
3,16/08/2025,Sunderland,West Ham,3,0,H,0,0,D,10,...,0,3.17,3.38,2.26,3.25,3.40,2.25,3.27,3.43,2.29
4,16/08/2025,Tottenham,Burnley,3,0,H,1,0,H,16,...,0,1.37,4.80,8.30,1.38,4.75,8.50,1.40,4.71,8.79
5,16/08/2025,Wolves,Man City,0,4,A,0,2,A,9,...,0,6.73,4.73,1.44,6.25,4.75,1.45,6.72,4.92,1.46
6,17/08/2025,Chelsea,Crystal Palace,0,0,D,0,0,D,19,...,0,1.61,4.21,5.08,1.62,4.33,4.50,1.66,4.12,5.25
7,17/08/2025,Nott'm Forest,Brentford,3,1,H,3,0,H,11,...,0,2.15,3.36,3.43,2.20,3.30,3.50,2.25,3.38,3.40
8,17/08/2025,Man United,Arsenal,0,1,A,0,1,A,22,...,0,3.57,3.56,2.01,3.60,3.60,1.95,3.74,3.72,2.01
9,18/08/2025,Leeds,Everton,1,0,H,0,0,D,21,...,0,2.39,3.29,2.96,2.38,3.30,3.00,2.37,3.52,3.06

In [23]:
new_df_2425 = df_2425[SELECTED_COLUMNS]
new_df_2425.head(10)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,...,AR,AvgH,AvgD,AvgA,B365H,B365D,B365A,PSH,PSD,PSA
0,16/08/2024,Man United,Fulham,1,0,H,0,0,D,14,...,0,1.62,4.36,5.15,1.60,4.20,5.25,1.63,4.38,5.30
1,17/08/2024,Ipswich,Liverpool,0,2,A,0,0,D,7,...,0,8.28,5.76,1.34,8.50,5.50,1.33,8.18,5.84,1.34
2,17/08/2024,Arsenal,Wolves,2,0,H,1,0,H,18,...,0,1.18,7.86,15.87,1.18,7.50,13.00,1.16,8.56,16.22
3,17/08/2024,Everton,Brighton,0,3,A,0,1,A,9,...,0,2.67,3.41,2.68,2.63,3.30,2.63,2.73,3.36,2.71
4,17/08/2024,Newcastle,Southampton,1,0,H,1,0,H,3,...,0,1.35,5.62,8.10,1.36,5.25,8.00,1.35,5.70,8.25
5,17/08/2024,Nott'm Forest,Bournemouth,1,1,D,1,0,H,14,...,0,2.45,3.49,2.89,2.45,3.50,2.80,2.47,3.42,2.97
6,17/08/2024,West Ham,Aston Villa,1,2,A,1,1,D,14,...,0,2.44,3.69,2.79,2.45,3.60,2.75,2.49,3.65,2.80
7,18/08/2024,Brentford,Crystal Palace,2,1,H,1,0,H,9,...,0,2.46,3.44,2.90,2.40,3.40,2.90,2.50,3.40,2.95
8,18/08/2024,Chelsea,Man City,0,2,A,0,1,A,10,...,0,4.05,4.00,1.83,4.10,3.90,1.80,4.19,3.93,1.84
9,19/08/2024,Leicester,Tottenham,1,1,D,0,1,A,7,...,0,5.01,4.37,1.63,5.00,4.33,1.62,5.09,4.39,1.63

In [24]:
new_df_2324 = df_2324[SELECTED_COLUMNS]
new_df_2324.head(10)

,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,HS,...,AR,AvgH,AvgD,AvgA,B365H,B365D,B365A,PSH,PSD,PSA
0,11/08/2023,Burnley,Man City,0,3,A,0,2,A,6,...,0,9.02,5.35,1.35,8.00,5.50,1.33,8.58,5.51,1.37
1,12/08/2023,Arsenal,Nott'm Forest,2,1,H,2,0,H,15,...,0,1.18,7.64,15.67,1.18,7.00,15.00,1.18,7.86,15.67
2,12/08/2023,Bournemouth,West Ham,1,1,D,0,0,D,14,...,0,2.69,3.44,2.64,2.70,3.40,2.55,2.70,3.47,2.71
3,12/08/2023,Brighton,Luton,4,1,H,1,0,H,27,...,0,1.33,5.52,9.61,1.33,5.50,9.00,1.33,5.65,9.61
4,12/08/2023,Everton,Fulham,0,1,A,0,0,D,19,...,0,2.24,3.43,3.30,2.20,3.40,3.30,2.27,3.45,3.35
5,12/08/2023,Sheffield United,Crystal Palace,0,1,A,0,0,D,8,...,0,3.12,3.24,2.41,3.00,3.30,2.38,3.28,3.22,2.43
6,12/08/2023,Newcastle,Aston Villa,5,1,H,2,1,H,17,...,0,1.76,3.88,4.61,1.75,3.75,4.60,1.77,3.92,4.77
7,13/08/2023,Brentford,Tottenham,2,2,D,2,2,D,11,...,0,2.73,3.63,2.50,2.75,3.40,2.45,2.76,3.65,2.55
8,13/08/2023,Chelsea,Liverpool,1,1,D,1,1,D,10,...,0,2.87,3.64,2.39,2.90,3.40,2.38,2.97,3.64,2.40
9,14/08/2023,Man United,Wolves,1,0,H,0,0,D,15,...,0,1.31,5.65,9.85,1.33,5.50,9.00,1.32,5.79,9.66